# Generated by Django 5.1.4 on 2025-01-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_hotel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(null=True, upload_to='hotel_images/'),
        ),
    ]
