# Generated by Django 5.1.4 on 2025-01-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_alter_hotel_image'),
    ]

    operations = [
    ]
