# Generated by Django 5.1.1 on 2025-01-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0008_alter_hotel_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(null=True, upload_to='country_images/'),
        ),
    ]
