# Generated by Django 5.1.5 on 2025-01-26 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0009_city_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='image',
        ),
    ]
