# Generated by Django 5.1.5 on 2025-01-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0010_remove_city_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(null=True, upload_to='country_images/'),
        ),
    ]
